#                 LOGIN API REQUESTS
#
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "cris12",
    "password": "123456"
}
###
POST https://blog-app-api-backend.vercel.app/api/login
Content-Type: application/json

{
    "username": "cris12",
    "password": "123456"
}
